import { useKunuStore } from '../../store/useKunuStore'

export function Profile() {
  const child = useKunuStore((state) => state.child)
  const parent = useKunuStore((state) => state.parent)
  const settings = useKunuStore((state) => state.settings)
  const update = useKunuStore((state) => state.updateSettings)
  const reset = useKunuStore((state) => state.resetDemo)
  return <main className="content-page"><header className="content-heading"><p className="eyebrow">Family space</p><h1>Made for {child.name}.</h1><p>{parent.name} · Memories and progress remain private on this device.</p></header><div className="profile-layout"><section className="profile-card"><div className="profile-character"><span>C</span></div><div><small>Explorer</small><h2>{child.name}</h2><p>Born {new Intl.DateTimeFormat('en', { dateStyle: 'long', timeZone: 'UTC' }).format(new Date(`${child.dateOfBirth}T12:00:00Z`))}</p></div></section><section className="settings-card"><h2>Sound & comfort</h2><SettingToggle label="Master audio" description="Enable all Kunu sounds" checked={settings.masterAudio} onChange={(value) => update({ masterAudio: value })}/><SettingToggle label="Music" description="Calm home and light adventure music" checked={settings.music} onChange={(value) => update({ music: value })}/><SettingToggle label="Ambience" description="Birds, wind, water, and footsteps" checked={settings.ambience} onChange={(value) => update({ ambience: value })}/><label className="volume-field"><span><strong>Volume</strong><small>{Math.round(settings.volume * 100)}%</small></span><input type="range" min="0" max="1" step=".05" value={settings.volume} onChange={(event) => update({ volume: Number(event.target.value) })}/></label><SettingToggle label="Reduced motion" description="Minimize transitions and camera movement" checked={settings.reducedMotion} onChange={(value) => update({ reducedMotion: value })}/><SettingToggle label="Reduced sensory" description="Soften flashes, particles, and layered sound" checked={settings.reducedSensory} onChange={(value) => update({ reducedSensory: value })}/></section><section className="privacy-card"><h2>Your family’s privacy</h2><p>Kunu has no account and no backend. Imported family photographs are stored in IndexedDB on this device and are never included in the app bundle. Demo art is original and stylized.</p><details><summary>Install Kunu</summary><p>On iPhone, open Share and choose Add to Home Screen. In desktop browsers, use the install icon in the address bar.</p></details><button className="danger-button" onClick={() => { if (window.confirm('Reset all local Kunu progress and settings?')) void reset() }}>Reset demo data</button></section></div></main>
}

function SettingToggle({ label, description, checked, onChange }: { label: string; description: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <label className="setting-toggle"><span><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)}/><i/></label>
}
